cora:
  seed: 39788
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  drop_scheme: "uniform"
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  tau: 0.87
  weight_decay: 0.00001
  num_epochs: 400 #400
  patience: 400 #400
  ts: 0.9
  batch: 0
citeseer:
  seed: 38108
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  drop_scheme: "uniform" #evc
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.2
  tau: 0.9
  weight_decay: 0.00001
  num_epochs: 400 #400
  patience: 400 #400
  ts: 0.1
  batch: 0

